version: '3'

services:
    database:
        image: arangodb
        environment:
            ARANGO_NO_AUTH: 1
        ports:
         - 8529:8529
        volumes:
         - data:/var/lib/arangodb3
         - data_app:/var/lib/aranagodb3-apps
        networks:
         - database

    web:
        build: backend
        env_file: .env
        depends_on:
         - database
        volumes:
         - ./backend:/var/src
        networks:
         - database
         - web

    frontend:
        build: frontend
        volumes:
         - ./frontend:/var/src
        depends_on:
         - web
        networks:
         - web

    nginx:
        image: nginx
        volumes:
         - ./config/nginx:/etc/nginx:ro
         - media:/media
        ports:
         - 80:8080
         # - 443:4430
        depends_on:
         - web
         - frontend
        networks:
         - web

volumes:
    data:
    data_app:
    media:

networks:
    database:
    web:
